/**
 * @typedef {{name: string, profileImage: string, email: string, phone: string, address: string, website: string, socialMedia: {[key: string]: string}}} Uploader
 }}
 */

 /**
  * @type {{[key: number]: Uploader}}
  */
const uploaders = {
    2:{
        name: "jeremy",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "jeremy@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://jeremy.com",
        socialMedia: {
            github: "https://github.com/jeremy",
            twitter: "https://twitter.com/jeremy",
            instagram: "https://instagram.com/jeremy",
            facebook: "https://facebook.com/jeremy",
        },
    },
    3:{
        name: "john",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        email: "john@example.com",
        phone: "987-654-3210",
        address: "456 Maple St",
        website: "https://john.com",
        socialMedia: {
            github: "https://github.com/john",
            twitter: "https://twitter.com/john",
            instagram: "https://instagram.com/john",
            facebook: "https://facebook.com/john",
        },
    },
    4:{
        name: "james",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "james@example.com",
        phone: "111-222-3333",
        address: "789 Elm St",
        website: "https://james.com",
        socialMedia: {
            github: "https://github.com/james",
            twitter: "https://twitter.com/james",
            instagram: "https://instagram.com/james",
            facebook: "https://facebook.com/james",
        },
    },
    5:{
        name: "jane",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "jane@example.com",
        phone: "444-555-6666",
        address: "101 Oak St",
        website: "https://jane.com",
        socialMedia: {
            github: "https://github.com/jane",
            twitter: "https://twitter.com/jane",
            instagram: "https://instagram.com/jane",
            facebook: "https://facebook.com/jane",
        },
    },
    6:{
        name: "jessica",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        email: "jessica@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://jessica.com",
        socialMedia: {
            github: "https://github.com/jessica",
            twitter: "https://twitter.com/jessica",
            instagram: "https://instagram.com/jessica",
            facebook: "https://facebook.com/jessica",
        },
    },
    7:{
        name: "maria",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        email: "maria@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://maria.com",
        socialMedia: {
            github: "https://github.com/maria",
            twitter: "https://twitter.com/maria",
            instagram: "https://instagram.com/maria",
            facebook: "https://facebook.com/maria",
        },
    },
    8:{
        name: "johnathan",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "johnathan@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://johnathan.com",
        socialMedia: {
            github: "https://github.com/johnathan",
            twitter: "https://twitter.com/johnathan",
            instagram: "https://instagram.com/johnathan",
            facebook: "https://facebook.com/johnathan",
        },
    },
    9:{
        name: "adam",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        email: "adam@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://adam.com",
        socialMedia: {
            github: "https://github.com/adam",
            twitter: "https://twitter.com/adam",
            instagram: "https://instagram.com/adam",
            facebook: "https://facebook.com/adam",
        },
    },
    10:{
        name: "emily",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "emily@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://emily.com",
        socialMedia: {
            github: "https://github.com/emily",
            twitter: "https://twitter.com/emily",
            instagram: "https://instagram.com/emily",
            facebook: "https://facebook.com/emily",
        },
    },
    11:{
        name: "brad",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "brad@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://brad.com",
        socialMedia: {
            github: "https://github.com/brad",
            twitter: "https://twitter.com/brad",
            instagram: "https://instagram.com/brad",
            facebook: "https://facebook.com/brad",
        },
    },
    12:{
        name: "lisa",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,  
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "lisa@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://lisa.com",
        socialMedia: {
            github: "https://github.com/lisa",
            twitter: "https://twitter.com/lisa",
            instagram: "https://instagram.com/lisa",
            facebook: "https://facebook.com/lisa",
        },
    },
    13:{
        name: "samantha",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,  
        email: "samantha@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://samantha.com",
        socialMedia: {
            github: "https://github.com/samantha",
            twitter: "https://twitter.com/samantha",
            instagram: "https://instagram.com/samantha",
            facebook: "https://facebook.com/samantha",
        },
    },
    14:{
        name: "joseph",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,  
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "joseph@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://joseph.com",
        socialMedia: {
            github: "https://github.com/joseph",
            twitter: "https://twitter.com/joseph",
            instagram: "https://instagram.com/joseph",
            facebook: "https://facebook.com/joseph",
        },
    },
    15:{
        name: "alex",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,  
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "alex@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://alex.com",
        socialMedia: {
            github: "https://github.com/alex",
            twitter: "https://twitter.com/alex",
            instagram: "https://instagram.com/alex",
            facebook: "https://facebook.com/alex",
        },
    },
    16:{
        name: "cody",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,  
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "cody@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://cody.com",
        socialMedia: {
            github: "https://github.com/cody",
            twitter: "https://twitter.com/cody",
            instagram: "https://instagram.com/cody",
            facebook: "https://facebook.com/cody",
        },
    },
    17:{
        name: "kyle",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,  
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "kyle@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://kyle.com",
        socialMedia: {
            github: "https://github.com/kyle",
            twitter: "https://twitter.com/kyle",
            instagram: "https://instagram.com/kyle",
            facebook: "https://facebook.com/kyle",
        },
    },
    18:{
        name: "isaac",
        profileImage: `https://avatars3.githubusercontent.com/u/${Math.floor(Math.random() * 10000)}?v=4`,  
        indexOfRecipes: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
        email: "isaac@example.com",
        phone: "123-456-7890",
        address: "123 Main St",
        website: "https://isaac.com",
        socialMedia: {
            github: "https://github.com/isaac",
            twitter: "https://twitter.com/isaac",
            instagram: "https://instagram.com/isaac",
            facebook: "https://facebook.com/isaac",
        },
    },
}

